# Generated by Django 4.1.5 on 2023-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='basic', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='users.group'),
        ),
    ]
