# Generated by Django 4.1.5 on 2023-01-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_product_teacher_remove_course_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoppers',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='members',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
