# Generated by Django 4.1.5 on 2023-02-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_product_shoppers_remove_seller_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
