# Generated by Django 4.1.5 on 2023-01-31 14:17

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_remove_product_shoppers_remove_seller_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tumb', models.ImageField(blank=True, upload_to=shop.models.course_tumb_directory_path)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, default=1000000, max_digits=7)),
                ('count', models.DecimalField(decimal_places=0, default=1, max_digits=7)),
                ('shoppers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('topic', models.CharField(choices=[('BP', 'Basic Programming'), ('AP', 'Advanced Programming'), ('CS', 'Computer Science'), ('MS', 'Mathematics'), ('CH', 'Chemistry'), ('BL', 'BioLogy'), ('PH', 'physics'), ('EL', 'Electronics'), ('RG', 'Religious'), ('Or', 'Other')], default='Or', max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 2, 1, 14, 17, 13, 896481))),
                ('price', models.DecimalField(decimal_places=0, default=1000000, max_digits=7)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='', max_length=255)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('tumb', models.ImageField(blank=True, upload_to=shop.models.course_tumb_directory_path)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=0, default=1000000, max_digits=7)),
                ('video', models.FileField(null=True, upload_to=shop.models.course_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='shop.teacher')),
                ('shoppers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
