# Generated by Django 4.1.5 on 2023-01-31 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 14, 19, 45, 217351)),
        ),
    ]
